### ISSUE TITLE
Padavan能用吗

### ISSUE THREAD

**Issue by FengNewp** [youshandefeiyang/SpeedTestCN-Auto#1]
H大的Padavan能用吗

**Comment by youshandefeiyang** [comment]
要安装jq

**Comment by youshandefeiyang** [comment]
你自己试试

**Comment by FengNewp** [comment]
curl -s 'https://tisu-api.speedtest.cn/api/v2/speedup/reopen?source=www' | jq .data
padavan可以直接运行这个，在设置一个定时脚本可以完美
