### ISSUE TITLE
请教大佬可否做一个重启路由器xx秒提速的命令么？谢谢

### ISSUE THREAD

**Issue by yishion819** [youshandefeiyang/SpeedTestCN-Auto#2]
教程的命令是定时的，但重启路由器后无法立刻提速，要等到定时才能运行脚本提速，谢谢

**Comment by youshandefeiyang** [comment]
因为要等待路由器成功联网后才执行，不可能刚开机就执行，那样是无法获取IP并且也没办法请求

**Comment by yishion819** [comment]
> 因为要等待路由器成功联网后才执行，不可能刚开机就执行，那样是无法获取IP并且也没办法请求

嗯，我知道，但比如10:03手动重启了，就必须要等到11点才能运行脚本，我的意思是可否弄一个命令，比如重启后5分钟或者10分钟运行脚本呢，谢谢

**Comment by youshandefeiyang** [comment]
现在就是5分钟后，300秒

**Comment by yishion819** [comment]
> 现在就是5分钟后，300秒

好的，谢谢，明白了
